### ISSUE TITLE
Remove unused source code to avoid problems

### ISSUE THREAD

**Issue by jpverhaeghe** [ACDfinalProject/Mario#1]
If you guys aren't using code (like background.java, and BascicRendering.java) then put them in an archive folder to help alleviate confusion amongst yourselves.

**Comment by aayushshah823** [comment]
Basic rendering is of no use, but background might help.


Thanks,

Aayush Shah
Sent from Yahoo Mail on Android

**Comment by aayushshah823** [comment]
Wait, what you mean by Assigned # 1 to me?

Aayush Shah
Sent from Yahoo Mail on Android

**Comment by jpverhaeghe** [comment]
If you think something is not of use, move it to an archive directory and commit. If that is all the files we don't need, then close the issue. If there might be more, then assign it to the next person.

This is how we solve issues in code development. If you have an issue, create it and assign it to the person you think should take care of it.

**Comment by ACDfinalProject** [comment]
How does one move something to an archive directory? I can find an "edit" function and a "delete" function, but no "new folder" function or anything of the like. Did you create your new files through gitHub or through this website itself?

**Comment by aayushshah823** [comment]
I am not sure how to move it but if code is of no use, just delete it.

**Comment by ACDfinalProject** [comment]
Ok, I think that takes care of our unwanted files. I have absolutely no clue what README.md or .gitignore are so I'm just going to leave them where they are.

**Comment by jpverhaeghe** [comment]
.gitignore is the list of ignored files on your local repository. This way you can have a .classpath, .project, and other files locally without it asking you to commit them each time. Also, it how you keep your Eclipse projects in different locations on other computers.

The Readme.md is the starting point for your documentation, and wiki pages. You guys don't need to worry about that now, but it is good to do if you plan to create a larger project that others will use - for example the space game project here:https://github.com/Mikeware/SpaceBattleArena/blob/master/README.md

To create an archive directory, you do it on your computer, move the files there, then commit the changes. You can't create a directory on the website. That is how I moved files to the src directory.
